### ISSUE TITLE
scripts in mission

### ISSUE THREAD

**Issue by BryanBoru** [alganthe/Co-ops#1]
Is there any way to add a view distance script similar to [CH View Distance Script](http://www.armaholic.com/page.php?id=27390) to the mission? I am enjoying this mission set very much however the most popular complaint I hear is the limitation of View Distance control and team management (but IIRC you added/are adding team management, I haven't played the recent release).

**Comment by alganthe** [comment]
added in latest stable.

**Comment by BryanBoru** [comment]
excellent. Thank you for the great mission!
