### ISSUE TITLE
Not compatible with ACE medical

### ISSUE THREAD

**Issue by alexcroox** [alganthe/Co-ops#25]
**Arma 3 Version:** stable <br/>
**Co-ops version** stable

**Client mods:**
- ACE
- RHS

**Description:**
- When a player dies Co-ops revive system puts them back on the spot, on their back. There is no scroll wheel action to revive them (just drag and carry). Normal ACE medical cannot be used to bring them back to life either as it shows all body parts as uninjured. The player is forced to hit respawn after a period of confusion.

**Where did the issue occur?**
- Dedicated

**Comment by alganthe** [comment]
disable it, remove the entry from the description.ext
It's intentional the system is supposed to be only used for vanilla and disabled when ace3 is present (or any other mod with a medical system)

**Comment by alexcroox** [comment]
OK thanks will give that a go.

When you say it's supposed to be disabled when ACE3 is present does that mean it's failing to detect the presence of ACE? Or did a misread that as being be automatic!

**Comment by alganthe** [comment]
no, just open the mission and remove the respawn entry
https://github.com/alganthe/Co-ops/blob/dev_altis/description.ext#L44
here, remove derp_revive.

**Comment by alexcroox** [comment]
Appreciate the help thank you!

**Comment by alganthe** [comment]
if you want I can add a check for future users, thoughts ?

**Comment by alexcroox** [comment]
Would be useful if it's not a ton of work to avoid having to edit the description.ext and re-build the mission manually every time you release a new version

**Comment by alganthe** [comment]
done in 2dd5e724e93f9e374d6db6a5182749cf5c931130

**Comment by alexcroox** [comment]
Thank you!

**Comment by alexcroox** [comment]
If we use ACE medial would you recommend we set the ACE settings server side to avoid having to make changes to your mission.sqm every time?

**Comment by alganthe** [comment]
it's up to you, the mission SQM shouldn't change from version to version, only the version number is changed inside it.

**Comment by alexcroox** [comment]
Ah that's good to know, I dropped a bunch of modules we use in it recently so if I can overwrite everything else every update that's great! (I will obviously check commit logs to ensure mission.sqm hasn't had changes).
