### ISSUE TITLE
Complete area objective when % of AI defeated

### ISSUE THREAD

**Issue by alexcroox** [alganthe/Co-ops#26]
Some feedback from players was around frustration when there is 1 or 2 enemy infantry remaining in the zone and with only 10 players it become tiresome hunting a very large area to find 1 guy hiding in the jungle somewhere.

A possible solution to this would be to complete the mission after a % of enemy in area have been killed, rather than every single one.

**Comment by alganthe** [comment]
it's currently 6 units left, I'll add a mission parameter for a % instead :+1:

**Comment by alganthe** [comment]
done.
