### ISSUE TITLE
Arsenal enabled

### ISSUE THREAD

**Issue by jus61** [alganthe/Co-ops#27]
If I put on "Arsenal enabled" then does not work ingam.

`class ArsenalFilter {
        title = "Filter mode of the arsenal";
        texts[] = {"Arsenal disabled", "Arsenal enabled but filtered", "Arsenal enabled"};
        values[] = {0, 1, 2};
        default = 2;
    };`

**Comment by alganthe** [comment]
Can you precise which version you are running, and what do you mean by "does not work"?
A new version with a reworked system is going to be released today or tomorrow.

Please note that if you're self hosting the issue is already fixed in 5a497138ac40f0f5eb80b40f229008be6e29859d

**Comment by alganthe** [comment]
Should be fixed in the new release: https://github.com/alganthe/Co-ops/releases/tag/1.4.350
