### ISSUE TITLE
Missing Fired Eventhandler for vehicles in Base

### ISSUE THREAD

**Issue by JohnnyDrama69** [alganthe/Co-ops#30]
**Arma 3 Version:** 1.66
**Co-ops version** 1.4.360

**Description:**
- You are able to fire vehicle guns in the base

**Steps to reproduce:**
- shoot a vehicle gun from any kind of vehicle in base

**Where did the issue occur?**
- Dedicated 

**Solution:**
- add a vehicle Eventhandler to the respawnable vehicles in base: 
 http://pastebin.com/B2BFCkX4
- add a vehicle Eventhandler to the side mission rewards:
http://pastebin.com/GHRBDt0G
- will not affect vehicles placed down by zeus

- maybe turn the "range"(default 300 i think) around the base marker in as a parameter for the description.ext, so if you transfer the base to another area or the whole mission to a new map, you can easily adjust this. or maybe turn it off on private server/ increase on public.
I think 300 is actually pretty low, specially for a public server.

**Comment by alganthe** [comment]
Not going to be an issue anymore, i'm going to use [FiredMan](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#FiredMan) instead

**Comment by BryanBoru** [comment]
tried a variation on this and I can't seem to get FiredMan to work. I noticed both your Master branch and Release Branch also both still have Fired, did you also find FiredMan wouldn't work?

**Comment by alganthe** [comment]
I haven't pushed to master branch yet, I push only stable release ready versions to it.

**Comment by BryanBoru** [comment]
I was completely at fault and it works fine. I had an error in my code.  Thanks for the reply. I forgot to delete this comment.
