### ISSUE TITLE
Base-AA attacking friendly "traitor" units

### ISSUE THREAD

**Issue by JohnnyDrama69** [alganthe/Co-ops#31]
**Arma 3 Version:** 1.66<br/>
**Co-ops version** 1.4.360 

**Description:**
- If a Pilot crashes a helicopter with people in it, it will count as TK, therefore lower his rating and possibly turn him into a "traitor". If he does not respawn and goes back to base, he will be attacked by AA. Sometimes even a hard landing in base is enough to turn someone into a traitor and therefore getting attacked by friendly AI

**Steps to reproduce:**
- Kill friendly units and then return to base. If you have killed enough units to make your rating go below 0, you will get attacked by friendly AI of any kind

**Where did the issue occur?**
- Dedicated 

**Solution:**
- make a script that ensures the rating of players is positive (found this one in a bohemia forums post)
- http://pastebin.com/jwgnchwh

**Comment by alganthe** [comment]
BIS issue, changing the rating of players comes with a bunch of problems, unless the pilot teamkills and doesn't die (squish a player or fire at friendlies) it shouldn't be an issue.

I'll leave this open for discussion for a while before closing
