### ISSUE TITLE
Problems with Anti-Map-drawing-script

### ISSUE THREAD

**Issue by JohnnyDrama69** [alganthe/Co-ops#32]
**Arma 3 Version:** `1.66` (stable / rc / dev) <br/>
**Co-ops version** `1.4.360` (beta / release)

**Description:**
- No matter which value I use (Yes/No) for the "Enable/Disable Map drawing"-parameter in mission selection, map drawing is always disabled on all channels

**Idea:**
- make it possible to enable/disable mapdrawing for specific radio channels. (e.g.: only disabled in Global, Side and Command-Chat)

**Where did the issue occur?**
- Dedicated

**Comment by alganthe** [comment]
This was a temporary fix until BIS introduced the server setting to disable map drawing.
The setting is:
`drawingInMap = 0; // 0 disabled; 1 enabled`
in server.cfg
