### ISSUE TITLE
Clean-up for Vehicle-Units added by Zeus not working correctly

### ISSUE THREAD

**Issue by JohnnyDrama69** [alganthe/Co-ops#33]
**Arma 3 Version:** `1.66` <br/>
**Co-ops version** `1.4.360` 

**Description:**
- Dead/disabled vehicles spawned in by the AO-"generator" will be cleaned up
- Additional vehicles spawned in by Zeus , that are turned into disabled (not destroyed) vehicles (->shoot the tires) will not be cleaned up
- It seems like when players disconnect in base, they leave behind a dead body, which does not seem to get cleaned up, at least not in a couple minutes.

**Steps to reproduce:**
- Use Zeus to spawn in enemy wheeled APC or trucks, shoot tires, crew gets out. disabled vehicle stays forever?
- disconnecting in base usually leaves behind a dead body of you (on dedicated)

**Where did the issue occur?**
- Dedicated

**Comment by alganthe** [comment]
That is intended behavior, it's to avoid a performance hog having to track all vehicles, zeus can just delete them.
Players bodies do get cleaned, I just kept the timer on it slightly long.
