### ISSUE TITLE
always heavy fog after about 15min into the game

### ISSUE THREAD

**Issue by JohnnyDrama69** [alganthe/Co-ops#35]
**Arma 3 Version:** `1.66` (stable / rc / dev) <br/>
**Co-ops version** `1.4.360` (beta / release)

**Client mods:**

 **Server mods:**

**Description:**
- when I start the mission, its clear and sunny
- after about 15-20min ingame, the fog is so strong, that you can barely see more than 200m
- tried multiple maps, affects all of them. 
- resetting the fog with Zeus weather module fixes it usually 

**Steps to reproduce:**
-  startup mission at 07:00 and 4 hour days; no shorter nights enabled.
- just wait in base

**Where did the issue occur?**
- Dedicated 

**Solution:**
- the base level of the fog is set to 250m in the mission, maybe this is the reason for such dense fog?

**Comment by alganthe** [comment]
BIS issue, fog on tanoa has a 200~ base value instead of 0, meaning that a low fog value on altis will result in a slight fog, and the same value on tanoa on a heavy as fuck fog.
