### ISSUE TITLE
Heli-CAS-reinforcements will get static if they do not see any enemy

### ISSUE THREAD

**Issue by JohnnyDrama69** [alganthe/Co-ops#51]
**Arma 3 Version:** `1.66` <br/>
**Co-ops version** `1.4.379` 

**Description:**
- Enemy Heli-CAS spawns, flies to AO with a Seek and Destroy waypoint. Finds no enemy and then just hovers over center of AO
- enemy Jet-CAS cant hover so it will keep flying around

**Idea/Solution:**
- Use a loiter waypoint to make it circle?

**Where did the issue occur?**
- Dedicated

**Comment by alganthe** [comment]
Can't use loiter, once the SAD waypoint is done the AI just sits there without anything to do, i'll generate some waypoints around the AO with a cycle waypoint so it doesn't stay static.
