### ISSUE TITLE
Does not work with ACE.

### ISSUE THREAD

**Issue by Doctor-Butts** [alganthe/Co-ops#55]
**Arma 3 Version:** `x.xx` (stable / rc / dev) <br/>
**Co-ops version** `x.xx` (beta / release)

**Client mods:**
ace, rhs

 **Server mods:**
ace, rhs

**Description:**
Cannot use ace functions to revive a downed player- need to be able to disable mission revive to  use ace revive system since ACE takes away FAKs

**Steps to reproduce:**
Got shot a bunch of times, tired combat medics.

**Where did the issue occur?**
Everywhere, dedicated server.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- **DON'T SEND SERVER RPTS PLEASE, JUST CLIENTS**

**Comment by alganthe** [comment]
It's intended, the revive system was designed for vanilla use cases, if you ran ACE use the ace system.

**Comment by Doctor-Butts** [comment]
Do I just comment out the respawnTemplates[] = {"MenuPosition", __EVAL(call
compile preprocessFileLineNumbers "functions\revive\fn_ace3Check.sqf")};
line in description.ext, then?

**Comment by alganthe** [comment]
Yes, or you can just change it to have whatever templates you use.
