### ISSUE TITLE
Only pilots can paradrop to AO

### ISSUE THREAD

**Issue by alexcroox** [alganthe/Co-ops#7]
**Arma 3 Version:** `1.60 stable`<br/>
**Co-ops version** `1.0.201`

**Client mods:**

RHS, TFR, ACE

 **Server mods:**
RHS

**Description:**
- Only pilots are given a parachute when para dropping into AO via arsenal area

**Steps to reproduce:**
- Take a slot that isn't a pilot, enable paradrop to AO option in mission params
- Paradrop to AO via scroll wheel in base, if non pilot you will fall to your death with a message "you are not allowed to do this, you are not a pilot"

**Where did the issue occur?**
- Dedicated

**Comment by alganthe** [comment]
Thanks I forgot to add a check for that, noted and consider it fixed for a hotfix release (tomorrow or late today)

**Comment by alexcroox** [comment]
Nice, any chance you could have the option when to pull the chute instead of it auto opening at 800m?

**Comment by alganthe** [comment]
Good suggestion, I'll add it, I need to first fix some issues but it'll be on my list.

**Comment by alganthe** [comment]
Fixed in 960c568f1c24ac43c458879082600bba47d882ed
