### ISSUE TITLE
[Feature request] Dynamic Paradrop to AO option based on available pilots

### ISSUE THREAD

**Issue by alexcroox** [alganthe/Co-ops#8]
It would be great to dynamically enable/disable the paradrop to AO option based on if there was a pilot in the server or not.

Also perhaps change the scope of the paradrops, for example, only SLs can choose to drop anywhere, squad mates can only paradrop on their SL's position (promotes team play and anti rambo play styles).

**Comment by alganthe** [comment]
Added in 047722d0c8c45ae99fe458f8e617afffa355ef37
